site_name: pymm
site_description: Complete Python-based microscopy control without Java dependencies
site_url: https://pymmcore-plus.github.io/
repo_url: https://github.com/pymmcore-plus
repo_name: pymmcore-plus
watch: ["docs"]

nav:
  - Home: 
    - index.md
    - Tags: tags.md
  - "useq-schema": "!include ./submodules/useq-schema/mkdocs.yml"
  - "pymmcore-plus": "!include ./submodules/pymmcore-plus/mkdocs.yml"
  - "pymmcore-widgets": "!include ./submodules/pymmcore-widgets/mkdocs.yml"
  - "pymmcore-gui": "!include ./submodules/pymmcore-gui/mkdocs.yml"


theme:
  name: material
  logo: assets/logo_trans.png
  font: false
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.content_next # next/previous links bottom of content
    - navigation.footer  # next/previous links in footer
    - navigation.icons
    - navigation.indexes
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    # - content.action.edit
    # - navigation.tracking
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: octicons/moon-24
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode



markdown_extensions:
  #- pymdownx.extra # markdown in html (includes commented extensions below)
  - mkdocs-typer
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"

plugins:
  - search
  - literate-nav # autegenerate nav from _gen_widgets
  - monorepo
  - tags
  - autorefs:
      resolve_closest: true
  - spellcheck:
      backends:
        - codespell:
            dictionaries: [clear]
  - api-autonav:
      modules:
        - submodules/useq-schema/src/useq
        # - submodules/pymmcore-plus/src/pymmcore_plus
        - submodules/pymmcore-widgets/src/pymmcore_widgets
        # - submodules/pymmcore-gui/src/pymmcore_gui
      exclude:
        - useq.pycromanager
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
            - https://cmap-docs.readthedocs.io/objects.inv
            - https://psygnal.readthedocs.io/en/latest/objects.inv
          options:
            docstring_section_style: list # or "table"
            docstring_style: "numpy"
            filters: ["!^_"]
            heading_level: 1
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            summary: true

hooks:
  - submodules/pymmcore-widgets/docs/_hooks.py
  
extra_javascript:
  - javascripts/termynal.js

extra_css:
  - styles/extra.css
  - styles/termynal.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pymmcore-plus