site_name: Python Micro-Manager Ecosystem
site_description: Complete Python-based microscopy control without Java dependencies

theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'light blue'
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.sections
    - navigation.tabs
    - navigation.top

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Ecosystem Overview: pymmcore-plus-ecosystem.md
